# Generated by Django 5.1.4 on 2025-03-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='payment_amount',
            new_name='amount',
        ),
    ]
