# Generated by Django 5.1.4 on 2025-03-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeewanjyoti_data', '0002_batterystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterystatus',
            name='device_id',
            field=models.CharField(default=70, max_length=50),
            preserve_default=False,
        ),
    ]
