# Generated by Django 5.1.4 on 2025-03-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeewanjyoti_user', '0003_customuser_description_customuser_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse')], default='USER', max_length=10),
        ),
    ]
