# Generated by Django 5.1.4 on 2025-07-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeewanjyoti_user', '0005_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
